"""Description of the changes

Revision ID: 3502d7f5e8e4
Revises: a207e1e4e860
Create Date: 2024-12-04 14:16:34.792961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3502d7f5e8e4'
down_revision = 'a207e1e4e860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_listings')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pending'"))
        batch_op.create_foreign_key(None, 'job_listing', ['job_id'], ['id'])
        batch_op.create_foreign_key(None, 'candidate', ['candidate_id'], ['id'])

    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.alter_column('employer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('job_status_updates', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_job_listing', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_listing', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_status_updates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_job_listing', 'job_listings', ['job_id'], ['id'])
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.alter_column('employer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('job_listings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('posted_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
