"""Initial migration

Revision ID: a09cffba4b18
Revises: 
Create Date: 2024-11-05 08:58:29.078238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a09cffba4b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_listings')
    op.drop_table('applications')
    op.drop_table('job_status_updates')
    op.drop_table('candidates')
    op.drop_table('employers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('employer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('employer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('candidates',
    sa.Column('candidate_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('experience', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job_status_updates',
    sa.Column('update_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.job_id'], name='job_status_updates_ibfk_1'),
    sa.PrimaryKeyConstraint('update_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applications',
    sa.Column('application_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'applied'"), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], name='applications_ibfk_1'),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.job_id'], name='applications_ibfk_2'),
    sa.PrimaryKeyConstraint('application_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job_listings',
    sa.Column('job_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('requirements', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.employer_id'], name='job_listings_ibfk_1'),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
